USE [MediaLibrary]
GO


/****** Object:  Table [cbcmgro_medialibrary].[FOLDERS]    Script Date: 7/21/2014 11:31:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOLDERS](
	[FOLDER_ID] [int] NOT NULL,
	[CNAME] [nvarchar](100) NULL,
	[ENAME] [nvarchar](100) NULL,
	[ENABLED] [varchar](1) NULL,
	[PARENT_ID] [int] NULL,
	[SQLSCRIPT] [nvarchar](2000) NULL,
	[ORDERBY] [varchar](255) NULL,
	[ORDERDIR] [varchar](50) NULL,
	[DOWNLOAD] [varchar](100) NULL,
 CONSTRAINT [PK_FOLDERS] PRIMARY KEY CLUSTERED 
(
	[FOLDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


